# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 133046b58a2e00100b4dd5a3c7cc90ffc26276ef6923b6d90d1bafa0b0eb06d20f6fb2c78d77c51aaeb7347982aac805f2e8179644d3618a589e91c652f86797

test:
  secret_key_base: fa42e48468368a34738800ac0a2cb4e1c914c313f66a3a56cc3b94cc8649d6ec6a0767a5d62e43cbadce695e05f0575b7fb4a8ab38998eabf121ab6a33413528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
